Update helpers.py
Update to address not able to add items to market commodity list that fixes the error I got.

2026-07-25 14:06:20,287 - WARNING - helpers.py:98 - $terrainenrichmentsystems_name; not found in commodity list, adding it.
2026-07-25 14:06:20,287 - ERROR - load.py:209 - Unexpected error: 'list' object has no attribute 'add'
2026-07-25 14:06:20,288 - ERROR - load.py:210 - Traceback:
Traceback (most recent call last):
  File "/home/jeffs/.var/app/io.edcd.EDMarketConnector/data/EDMarketConnector/plugins/ArchitectTracker/load.py", line 156, in journal_entry
    helpers.save_facility_requirements(resources, station, mid)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeffs/.var/app/io.edcd.EDMarketConnector/data/EDMarketConnector/plugins/ArchitectTracker/helpers.py", line 141, in save_facility_requirements
    compare_material_to_list(materials)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/jeffs/.var/app/io.edcd.EDMarketConnector/data/EDMarketConnector/plugins/ArchitectTracker/helpers.py", line 101, in compare_material_to_list
    COMMODITIES.add(name)
    ^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'